name: userverse

description: "An app that shares user information"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8
  lottie: ^3.1.3
  skeletonizer: ^1.4.2

  # Navigation
  go_router: ^14.3.0

  # Dependency Injection
  get_it: ^8.0.1

  # State Management
  flutter_bloc: ^8.1.6

  # Local Storage
  shared_preferences: ^2.3.2

  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.3
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
          style: normal

        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
          style: normal

        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
          style: normal

        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
          style: normal

        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
          style: normal

        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
          style: normal